### ISSUE TITLE
Compare to dull

### ISSUE THREAD

**Issue by briatte** [Bart6114/jug#1]
Hi,

Would you mind explaining how `jug` differs from @nteetor's `dull` package?

> https://github.com/nteetor/dull

I'm new to Web frameworks, sorry in advance if the differences are obvious.

**Comment by nteetor** [comment]
Hey briatte,

There's very little difference as of now. It looks like Bart6114 is also using a paradigm similar to that of expressjs, which was and still is my inspiration for dull, and we are both using R6 classes for the guts of our work. A difference is the project descriptions. jug's is, as of now, "easily create R APIs" whereas dull is intended as a more general web framework for R. I'll be interested to see how different jug is from dull  in the end. 

nteetor

**Comment by briatte** [comment]
Thanks for the info. I'mll be interested in the same thing :)

Cheers to you both,

- François
