### ISSUE TITLE
Support for basic authorization

### ISSUE THREAD

**Issue by kylebalkissoon** [Bart6114/jug#10]
Support for basic authorization would be perfect for datasets that need to be protected and enable this to be used to connect R to a variety of tools securely.

**Comment by Bart6114** [comment]
For http authentication of type "basic" (see e.g. https://www.httpwatch.com/httpgallery/authentication/). We could do something like the following. 

Let's say we add the following middleware function:

```
auth_basic<-function(account_eval_func){
  function(req, res, err){
    
    auth_error <- function(){
      res$set_status(401)
      res$text("Basic authentication error")
    }
    
    if(is.null(req$get_header("authorization"))){
      auth_error()
    } else {
      auth_header <- unlist(strsplit(req$get_header("authorization"), " "))
      auth_type <- auth_header[1]
      auth_userpass <- unlist(strsplit(rawToChar(base64enc::base64decode(auth_header[2])), ":"))
      if(!all(tolower(auth_type) == "basic", account_eval_func(auth_userpass[1], auth_userpass[2]))){
        auth_error()
      }
      return(NULL)
    }
  }
}
```

In order to use it we must pass it a`account_eval_func` in order to validate whether or not a username / password  combination is valid. Here an example:

```
account_checker <- function(username, password){
  # do something to verify the username and password and return TRUE if combination OK
  all(username == "test_user", password == "test_password")
}
```

Let's try it for a specific path (`/test`):

```
jug() %>%
  get("/", function(req, res, err){
  "/ req"
  }) %>%
  get("/test", auth_basic(account_checker), function(req, res, err){
    "/test req"
  }) %>%
  serve_it()
```

Or for all the requests that the jug instance gets:

```
jug() %>%
  use(NULL, auth_basic(account_checker)) %>%
  get("/", function(req, res, err){
    "/ req"
  }) %>%
  serve_it()
```

What do you think about this approach?

**Comment by kylebalkissoon** [comment]
That actually works surprising well, thanks a lot! I've just changed the acctchecker to query a db instead.

**Comment by Bart6114** [comment]
Good to hear.
Reopening this until the code is merged as a new middleware into the dev version of `jug`.

Note to self: look into `auth_digest`

**Comment by kylebalkissoon** [comment]
Added fix to cover NA's user's trying to circumvent the rejection test.

`auth_basic<-function(account_eval_func){
  function(req, res, err){
    
    auth_error <- function(){
      res$set_status(401)
      res$text("Basic authentication error")
    }
    
    if(is.null(req$get_header("authorization"))){
      auth_error()
    } else {
      auth_header <- unlist(strsplit(req$get_header("authorization"), " "))
      auth_type <- auth_header[1]
      auth_userpass <- unlist(strsplit(rawToChar(base64enc::base64decode(auth_header[2])), ":"))
      if(any(is.na(auth_userpass))){
        auth_error()
      }
      if(!all(tolower(auth_type) == "basic", account_eval_func(auth_userpass[1], auth_userpass[2]))){
        auth_error()
      }else
        
        
      
      return(NULL)
    }
  }
}
`

**Comment by Bart6114** [comment]
Thanks, included it in the commit.
