### ISSUE TITLE
How to return HTTP errors from handling functions?

### ISSUE THREAD

**Issue by bhaskarvk** [Bart6114/jug#11]
From the document it's not very clear to me how to return HTTP errors from functions?
e.g. if the input params are missing or not in correct format, I want to throw 500 - Bad Request from the function. Not fully clear on how to do that.

**Comment by Bart6114** [comment]
Hi @bhaskarvk,

Below you can find the simplest solution. Note the explicit use of an error handler.

```r
library(jug)
library(magrittr)

say_hello<-function(name){paste("hello",name,"!")}

jug() %>%
  get("/", decorate(say_hello)) %>%
  simple_error_handler_json() %>%
  serve_it()
```
```
{
  "status": "error",
  "status_code": 500,
  "error": "Error in paste(\"hello\", name, \"!\") : \n  argument \"name\" is missing, with no default\n"
}
```

In the latest release (not on CRAN yet, install using `devtools::install_github`) you can also do:

```r
jug() %>%
  get("/", decorate(say_hello, strict_params=T)) %>%
  simple_error_handler_json() %>%
  serve_it()
```

Note here the use of `strict_params`. `jug` will test whether all required parameters are actually in the call, if not it will create an error which tells you which arguments have to be provided:

```
{
  "status": "error",
  "status_code": 500,
  "error": "Requested arguments not provided: name"
}
