### ISSUE TITLE
Basic authentication Preflight cors error

### ISSUE THREAD

**Issue by louisza** [Bart6114/jug#15]
When creating a basic authentication jug to be consumed by an AJAX call from a web app results in a CORS failure. It expects to receive a response with a list of headers containing at least the headers in the preflight OPTION request.

My example jug:

jug() %>% 
  cors(allow_methods = c("POST", "GET", "PUT","OPTIONS","DELETE", "PATCH"),
       allow_origin = '*',
       allow_headers = c('Origin', 'X-Requested-With', 'Content-Type', 'Accept', 'Authorization')
       ) %>%
  use(NULL, auth_basic(account_checker)) %>%
  get("/test", decorate(procTest)) %>%
  simple_error_handler() %>%
  serve_it(host="###.###.###.###") 

This starts a jug that I can call easily using curl and some other tools, but as soon as it is called using something like:

function ajax() {
    $.ajax({
      method: "GET",
      url: "http://###.###.###.###:8080/test",
      beforeSend: function(xhr) {
        xhr.setRequestHeader("Authorization", "Basic " + btoa("jug:!s@w35om3"));
      },
      dataType: "json",
      data: "jsonrequest=" + JSON.stringify(jsonRequestData) + ""
    }).done(function (responseData) {
      console.log(responseData);
    }).fail(function () {
      console.log("Error - AJAX call failed to retrieve response data.");
    });
  };

It fails with error: 

"Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 403."

I fixed it (or got a workaround, as I'm not 100% convinced of my solution) with this commit:

https://github.com/louisza/jug/commit/24bf04da74acb3370cb7c3f596a0609b07ac19ad

**Comment by Bart6114** [comment]
Hi @louisza, thanks for the work on the bugfix! Could you please create a pull request?

**Comment by Bart6114** [comment]
I've merged the commit, did some minor changes and added testing. Could you verify that you example works now with the latest version of the master branch? If so, this issue can be closed and I will submit a new version to CRAN.

**Comment by louisza** [comment]
Thx, working perfectly.
