### ISSUE TITLE
Failing on CORS allow_origin

### ISSUE THREAD

**Issue by ReeSilva** [Bart6114/jug#17]
Hey Bart, hope you've been doing well.

I'm having a problem with CORS and, since I'm not an expert in R I've decide to post here and ask for your help.

I have on my code the step to add endpoints. Here is the snippet:
```
#' Endpoints to RLang API
#'
#' Define all endpoints to R API
#'
#' @export
start_api <- function() {
  jug() %>%
    cors(allow_origin="*") %>%
    use("/check_api", function(req, res, err){
      "I'm alive!"
    }) %>%

    ...

    simple_error_handler_json() %>%
    serve_it(host="0.0.0.0")
}
```

But, when I make a request to check_api endpoint, the preflight isn't returning the allow_origin header:
```
Allow →POST,GET,PUT,OPTIONS,DELETE,PATCH
Content-Length →0
Content-Type →text/html
```
> This is the return of the request.

Am I doing something wrong or it is really a bug?

Thanks in advance.

**Comment by Bart6114** [comment]
hi @ReeSilva, I think this relates to #15. If so, this is fixed in the latest dev version.
Can you try installing `jug` using `devtools::install_github('bart6114/jug')` and see if that fixes it for you? I will push the latest dev version to CRAN later this week.

**Comment by ReeSilva** [comment]
I've tried it yesterday and didn't work, but today magically worked LOL Thanks a lot
