### ISSUE TITLE
add logging middleware

### ISSUE THREAD

**Issue by Bart6114** [Bart6114/jug#23]
logging middleware which writes request info to logfile
cfr. useR! conf

**Comment by nuest** [comment]
Do you have a specific logging package in mind already? I've been using `futile.logger` but maybe there's something else around.

**Comment by Bart6114** [comment]
Thanks for the tip, will look into it.

I thought this would be a simple extra middleware to create but I need to introduce a sort of 'hooks' concept for this to work. Normally after a successful response it will be immediately returned without going through other middleware, however, with logging you want to attach to a 'final hook' to log some details about the output of the final middleware and response it created. 
This should be normally be ready to go in approx. 2-4 weeks.

**Comment by bart6114** [comment]
Events and event listeners have been introduced in the latest dev branch, as well as a logger which makes use of this (built on top of `futile.logger`). Check the dev vignette for more info & examples.
