### ISSUE TITLE
Raw body of Post

### ISSUE THREAD

**Issue by mmilleruva** [Bart6114/jug#3]
Not sure if this is in your feature list, but I had to use a bit of a hack to get the raw body out of a post message:

```R
post("/", function(req, res, err){
  input <- req$raw$rook.input
  postdata <- input$read_lines()
```

Reading the docs, it seamed like there should be an easier way to do this. Perhaps the version on cran is old?

**Comment by Bart6114** [comment]
Just to clarify, would you like easy access to the object you defined as `input` or to the `postdata`?

In the latest version on github the `req$body` is equal to your `postdata`. Just try a `devtools::install_github("bart6114/jug")`

Or do you actually want the raw bytes (i.e. not a character string)?

**Comment by mmilleruva** [comment]
Perfect. No, I am just pulling a version from CRAN, which must be older.
