### ISSUE TITLE
HTTP OPTIONS request

### ISSUE THREAD

**Issue by mmilleruva** [Bart6114/jug#4]
Can jug handle http  `OPTIONS` requests? The library works great, but I am running into some Cross-Origin Resource Sharing issues.

**Comment by Bart6114** [comment]
There is no `options` convenience function for now like there is for `get` etc. 
I did however adjust the `use` method a bit to allow it to accept a `method` parameter (you'll have to do a reinstall from github).

This means you can do e.g.

```r
jug() %>%
  use("/", function(req, res, err){
    res$set_header("Allow", 'GET,HEAD,POST')
    "see allow header"
  }, method="OPTIONS") %>%
  serve_it()
```

Would this work for you?

**Comment by mmilleruva** [comment]
That does seem to work and I am able to get past the initial OPTIONS request, but I am still seeing issues in the browser specifying "Access-Control-Allow-Origin" has not been set. Have you ever successfully implemented a CORS enabled API with jug?

**Comment by Bart6114** [comment]
For me this seems to work; and actually makes me think that I should set the `Access-Control-Allow-Origin` header default to `*` unless specified otherwise.

For `res$set_header("Access-Control-Allow-Origin", '*')` I get the following results (using the console while at another webpage):

```
> var xhr = new XMLHttpRequest();
xhr.onload = function() {
   console.log(xhr.responseText);
};
xhr.open('POST', 'http://localhost:8080');
xhr.send();
< undefined
[Log] {"strategy":"random_forest","variation":"random_forest","adxFloor":"NA"}
```

If I set `res$set_header("Access-Control-Allow-Origin", 'bla')`, I get:

```
> var xhr = new XMLHttpRequest();
xhr.onload = function() {
   console.log(xhr.responseText);
};
xhr.open('POST', 'http://localhost:8080');
xhr.send();
< undefined
[Error] XMLHttpRequest cannot load http://localhost:8080/. Origin http://www.howmanygoats.com is not allowed by Access-Control-Allow-Origin.
```

Would you expect another behaviour?

**Comment by mmilleruva** [comment]
Doing some further research, this did end up working for me

**Comment by mmilleruva** [comment]
Thanks for your help with this. We are using Jug to prototype a prediction API that will get approx. 15 million requests a day. We are going to initially test this on a small percent of traffic with a number of docker instances to handle the load. I will let you know how the server handles a high volume of traffic and any other edge cases we encounter. Thanks for the great project!

**Comment by Bart6114** [comment]
Thanks @mmilleruva. Nice to hear that you will be using jug. Let me know if you encounter any issues! Definitely interested in getting feedback on high loads.

In the latest master branch you can now find an early version of `cors()` (check `?cors`). Using this your code would look like:

```r
jug() %>%
  cors("/", 
       allow_methods=c("POST","GET", "PUT", "OPTIONS", "DELETE", "PATCH"),
       allow_origin="*",
       max_age=3600,
       allow_headers=c("Origin", "X-Requested-With", "Content-Type", "Accept")) %>%
  get("/", ... get request logic ...) %>%
  ... further middlewares ...

```
